server:
  port: 8089
  #生产证书本地
  #keytool -genkey -alias https -keyalg RSA -keystore javastack.keystore
  ssl:
    protocol: TLS
    key-store: classpath:javastack.keystore
    key-password: javastack
    key-store-type: JKS
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      inital-size: 2
      max-active: 5
      min-idle: 2
      max-wait: 1000

      log-abandoned: true
      pool-prepared-statements: true
  rabbitmq:
    host: 192.168.99.100
    username: guest
    password: guest
    port: 5672
    publisher-returns: true
    publisher-confirm-type: simple
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        prefetch: 100

  redis:
    host: localhost
    port: 6379
    password: root
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 5000

mqtt:
  username: admin
  password: admin
  url: tcp://192.168.99.100:1883
  client:
    id: mqttjs_bca03e9d9a
  default:
    topic: topic22
  completionTimeout: 10000
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.entity
  configuration:
    map-underscore-to-camel-case: true
#showSql
logging:
  level:
    com:
      code: info
      alibaba: info
